public class CreatingAccount {
    
    public static Account createAccount(String name){
        
        Account newAccount = new Account();
        //Contact contactForCompany = new Contact ();
        //Lead decemberLead = new Lead ();
        newAccount.name = name;
        return newAccount;
        
    }
    
    //public String createText(String name){
        
        //code to execute
    //}
    

}